server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /${segment}
            - AddResponseHeader=Cache-Control, max-age=3600, public
            - AddResponseHeader=X-Gateway-Cache, HIT-MOCK

        - id: billing-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/api/billing/**
          filters:
            - RewritePath=/api/billing/(?<segment>.*), /${segment}
            - AddResponseHeader=Cache-Control, no-cache
            - AddResponseHeader=X-Gateway-Cache, MISS
