# Application Properties - Exercise 2: RESTful Web Services

# Server port
server.port=8083

# Logging Configuration
logging.level.org.springframework=info
logging.level.com.cognizant.springlearn=debug
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n

# Include exception message in error responses (for testing)
server.error.include-message=always
server.error.include-binding-errors=always
